# Criar o conta do usuario
POST "http://localhost:5050/signUp"
Content-Type: application/json

{
    "name": "kariel",
    "email": "kariel@gmail.com",
    "password": "Kariel@1",
    "confpassword": "Kariel@1"
}

#Rotar inicial

GET "http://localhost:5050"